import { _electron as electron,expect } from '@playwright/test';
import Database from 'better-sqlite3';
import { mkdir,cp,writeFile } from 'node:fs/promises';
import path from 'node:path';

const root=path.resolve(`.test-data/draft-ux-${Date.now()}`);await mkdir(root,{recursive:true});
const original=new Database('data/local/tchim.sqlite',{readonly:true});await original.backup(path.join(root,'tchim.sqlite'));original.close();
await cp('data/local/icons',path.join(root,'icons'),{recursive:true});
const env={...process.env,TCHIM_DATA_DIR:root,TCHIM_OFFLINE:'1',TCHIM_TEST_HEADLESS:'1'};delete env.ELECTRON_RUN_AS_NODE;
const executablePath=process.env.TCHIM_TEST_EXECUTABLE;
const desktop=await electron.launch({args:executablePath?[]:['.'],...(executablePath?{executablePath}:{}),env,timeout:30000});
const errors=[];
try{
 const page=await desktop.firstWindow();page.on('pageerror',e=>errors.push(e.message));
 await expect(page.getByTestId('app')).toBeVisible();
 await page.evaluate(async()=>{
  await window.draftApi.reset();await window.draftApi.configure({mode:'pro',side:'blue',targetRole:'AUTO',league:'all'});
  const empty={url:'',region:'euw',poolOnly:false,message:'',players:[]};await window.draftApi.teams({ally:empty,enemy:empty});
  const s=await window.draftApi.snapshot();await window.draftApi.settings({...s.settings,poolOnly:false,language:'fr'});
  for(let i=0;i<6;i++)await window.draftApi.select(null);
 });
 const analysis=await page.evaluate(()=>window.draftApi.analyze());
 expect(analysis.picks.length).toBeGreaterThan(5);
 const region=page.getByTestId('recommendation-scroll');
 await expect(region.locator('.recommendation')).toHaveCount(analysis.picks.length,{timeout:30000});
 await expect(region).toHaveAttribute('aria-busy','false');
 expect(await region.evaluate(e=>e.scrollHeight>e.clientHeight)).toBe(true);
 await region.locator('.recommendation').nth(12).scrollIntoViewIfNeeded();
 expect(await region.evaluate(e=>e.scrollTop)).toBeGreaterThan(0);
 const snapshot=await page.evaluate(()=>window.draftApi.snapshot());
 const chosen=analysis.picks[12],name=snapshot.champions.find(c=>c.id===chosen.championId).name;
 const search=page.getByRole('textbox',{name:'Rechercher parmi les picks…',exact:true});
 await search.fill('aucun-champion-test');await expect(region.locator('.recommendation')).toHaveCount(0);
 await expect(region).toContainText('Aucun champion ne correspond');
 await page.getByRole('button',{name:'Effacer la recherche',exact:true}).click();
 await expect(region.locator('.recommendation')).toHaveCount(analysis.picks.length);
 await search.fill(name);await expect(region.locator('.recommendation')).toHaveCount(1);
 await expect(region.locator('.rec-position')).toHaveText('13');
 await region.getByRole('button',{name:`Choisir ${name}`,exact:true}).click();
 await page.getByRole('button',{name:'Valider',exact:true}).click();
 await expect(page.locator('.timeline-track .done')).toHaveCount(7);
 const picked=await page.evaluate(()=>window.draftApi.snapshot());
 expect(picked.draft.history[6]).toEqual({championId:chosen.championId,role:chosen.role});
 await expect(search).toHaveValue('');
 await page.getByRole('button',{name:'Annuler la dernière action',exact:true}).click();
 await expect(page.locator('.timeline-track .done')).toHaveCount(6);
 await page.evaluate(async()=>{await window.draftApi.select('Jinx','ADC');await window.draftApi.select('Vi','JUNGLE');await window.draftApi.select('Akali','MID');});
 const before=await page.evaluate(()=>window.draftApi.analyze());
 const meter=page.getByTestId('draft-balance').getByRole('meter');
 await expect(meter).toHaveAttribute('aria-valuenow',String(before.balance.value),{timeout:30000});
 await search.fill('Lulu');await expect(region.locator('.recommendation')).toHaveCount(1,{timeout:30000});
 await region.getByRole('button',{name:'Choisir Lulu',exact:true}).click();await page.getByRole('button',{name:'Valider',exact:true}).click();
 const after=await page.evaluate(()=>window.draftApi.analyze());expect(after.balance.value).not.toBe(before.balance.value);
 await expect(meter).toHaveAttribute('aria-valuenow',String(after.balance.value),{timeout:30000});
 await expect(page.getByTestId('draft-balance')).toContainText('4/10 picks révélés');
 await desktop.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(1440,1000);w.showInactive();});
 await page.evaluate(()=>window.scrollTo(0,0));
 const layout=await region.evaluate(e=>({top:e.getBoundingClientRect().top,viewport:window.innerHeight,firstBottom:e.querySelector('.recommendation').getBoundingClientRect().bottom,secondBottom:e.querySelectorAll('.recommendation')[1].getBoundingClientRect().bottom}));
 expect(layout.secondBottom).toBeLessThan(layout.viewport);
 await page.screenshot({path:'artifacts/draft-ux-viewport.png',fullPage:false});
 await page.screenshot({path:'artifacts/draft-ux-blue.png',fullPage:true});
 await page.evaluate(()=>window.scrollTo(0,500));
 await expect(page.getByTestId('draft-balance')).toBeInViewport({ratio:1});
 expect((await page.getByTestId('draft-balance').boundingBox()).y).toBeLessThan(20);
 await page.screenshot({path:'artifacts/draft-ux-scrolled.png',fullPage:false});
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.evaluate(()=>window.draftApi.configure({side:'red'}));
 await expect(page.getByTestId('draft-balance')).toHaveClass(/red/);
 await expect(meter).toHaveAttribute('aria-valuenow',String(-after.balance.value));
 await expect(page.locator('.balance-team-labels>span').first()).toContainText('Rouge');
 await expect(page.locator('.turn-guide')).toContainText('Renseignez le pick adverse');
 const nextWindow=desktop.waitForEvent('window');await page.getByRole('button',{name:'Overlay',exact:true}).click();const overlay=await nextWindow;
 await expect(overlay.getByTestId('draft-balance').getByRole('meter')).toHaveAttribute('aria-valuenow',String(-after.balance.value),{timeout:30000});
 await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('overlay=1')).showInactive());
 await overlay.screenshot({path:'artifacts/draft-ux-overlay.png'});
 await page.getByRole('button',{name:'Annuler la dernière action',exact:true}).click();
 await expect(meter).toHaveAttribute('aria-valuenow',String(-before.balance.value),{timeout:30000});
 await expect(overlay.getByTestId('draft-balance').getByRole('meter')).toHaveAttribute('aria-valuenow',String(-before.balance.value),{timeout:30000});
 await page.evaluate(()=>window.draftApi.overlay());
 await page.evaluate(async()=>{
  await window.draftApi.reset();
  const blue=[['Jinx','ADC'],['Lulu','SUPPORT'],['Ornn','TOP'],['Orianna','MID'],['Sejuani','JUNGLE']];
  const red=[['Vi','JUNGLE'],['Akali','MID'],['Ashe','ADC'],['Nautilus','SUPPORT'],['Gwen','TOP']];
  const order=['b','b','b','b','b','b','blue','red','red','blue','blue','red','b','b','b','b','red','blue','blue','red'];
  for(const side of order){if(side==='b')await window.draftApi.select(null);else{const [id,role]=(side==='blue'?blue:red).shift();await window.draftApi.select(id,role);}}
 });
 await expect(page.locator('.recommendation-heading h2')).toHaveText('Draft terminée',{timeout:30000});
 await expect(page.getByTestId('draft-balance')).toContainText('Les deux compositions sont complètes');
 await expect(region).toContainText('Les deux compositions sont complètes');
 await expect(search).toHaveCount(0);
 await page.screenshot({path:'artifacts/draft-ux-complete.png',fullPage:true});
 expect(errors).toEqual([]);
 await writeFile('artifacts/draft-ux-report.json',JSON.stringify({executablePath,pickCount:analysis.picks.length,selectedRank:13,layout,before:before.balance,after:after.balance,complete:(await page.evaluate(()=>window.draftApi.analyze())).balance,rendererErrors:errors},null,2));
 console.log('DRAFT_UX_OK all ranked picks, scrolling, search, selection beyond top 5, live gauge, undo, both sides, overlay sync, complete draft');
}finally{await desktop.close();}
